stateDiagram
  direction TB
  
  state MatrizApagada_NoMux <<choice>>
  
  [*] --> Desconectado: Inicio/Fallo de Conexión
  
  Desconectado --> Conectado: Conexión BLE Exitosa
  
  Conectado --> MatrizApagada_NoMux: Inicialización
  
  MatrizApagada_NoMux --> Multiplexando: Dato Recibido (1+ LEDs ON)
  Multiplexando --> MatrizApagada_NoMux: Dato Recibido (0 LEDs ON)
  
  Conectado --> Desconectado: Dispositivo Desconectado (BLE)
  MatrizApagada_NoMux --> Desconectado: Dispositivo Desconectado (BLE)
  Multiplexando --> Desconectado: Dispositivo Desconectado (BLE)
  
  state Desconectado {
      [*] --> BuscandoBLE
      BuscandoBLE --> Publicidad
      Publicidad --> BuscandoBLE : Tiempo de Publicidad Expira
      state Note: Sistema en Reposo, Sin Alimentación de LEDs
  }
  
  state Conectado {
      [*] --> EsperandoDatos
      EsperandoDatos --> EsperandoDatos : Monitoreo Periódico de Batería
      state Note: Esperando Comandos, Matriz Apagada
  }
  
  state Multiplexando {
      [*] --> Scanning
      Scanning --> Scanning : Procesa el siguiente LED en la secuencia
      state Note: Ciclo Activo de Encendido/Apagado de Filas
  }