%%{init: {'theme': 'default'}}%%
graph TD
    Usuario((Usuario))
    AppWeb((Aplicación Web BLE))
    ESP32((Controlador ESP32))

    %% Casos de uso
    gestionarConexion[[Gestionar Conexión BLE]]
    controlIndividual[[Controlar LED Individual]]
    controlMasivo[[Controlar Todos los LEDs]]
    monitorearBateria[[Monitorear Nivel de Batería]]
    
    %% Relaciones
    Usuario --> AppWeb
    
    AppWeb --> gestionarConexion
    AppWeb --> controlIndividual
    AppWeb --> controlMasivo
    AppWeb --> monitorearBateria
    
    controlIndividual -->|Envío de Estado (3 bytes)| ESP32 
    controlMasivo -->|Envío de Estado (3 bytes)| ESP32 
    
    ESP32 -->|Lectura ADC| monitorearBateria
    
    ESP32 -.->|Reporte de Voltaje| AppWeb