%%{init: {'theme': 'default'}}%%
graph TD
    Usuario((Usuario))
    AppWeb((Aplicación Web BLE))
    ESP32((Controlador ESP32 - Firmware))

    %% Casos de uso de la App Web
    gestionarConexion[[1. Gestionar Conexión BLE - Conectar/Desconectar]]
    cambiarEstadoLED[[2. Enviar Estado de LED Individual]]
    controlMasivo[[3. Enviar Estado de Todos los LEDs - On/Off]]
    monitorearBateria[[4. Mostrar Nivel de Batería]]
    visualizarRegistro[[5. Visualizar Registro de Eventos]]
    
    %% Flujos de datos/control
    Usuario --> AppWeb
    
    AppWeb --> gestionarConexion
    AppWeb --> cambiarEstadoLED
    AppWeb --> controlMasivo
    AppWeb --> visualizarRegistro
    
    cambiarEstadoLED -->|WRITE Nuevo Estado LED (3 bytes)| ESP32 
    controlMasivo -->|WRITE Nuevo Estado (3 bytes)| ESP32 
    
    ESP32 -->|Lee pin ADC| monitorearBateria
    
    ESP32 -.->|Lectura Voltaje Batería| AppWeb