stateDiagram
  direction TB
  
  state Eleccion_de_Accion <<choice>>
  
  [*] --> Desconectado: Inicio/Fallo de Energía
  
  Desconectado --> Conectado: Enlace BLE Establecido
  
  Conectado --> Eleccion_de_Accion: Inicio de Operación
  
  Eleccion_de_Accion --> Multiplexando: Comando Recibido (LEDs ON)
  Eleccion_de_Accion --> Esperando_Comando: Comando Recibido (LEDs OFF)
  
  Esperando_Comando --> Multiplexando: Nuevo Comando ON
  Multiplexando --> Esperando_Comando: Comando OFF Recibido
  
  Conectado --> Desconectado: Conexión BLE Perdida
  Esperando_Comando --> Desconectado: Conexión BLE Perdida
  Multiplexando --> Desconectado: Conexión BLE Perdida
  
  state Desconectado {
      [*] --> Publicidad_BLE
      Publicidad_BLE --> Publicidad_BLE : Ciclo de Anuncio
      state Note: Bajo consumo, a la espera de un cliente.
  }
  
  state Esperando_Comando {
      [*] --> Monitoreando_Bateria
      Monitoreando_Bateria --> Monitoreando_Bateria : Ejecuta Tarea de Monitoreo
      state Note: Pines en LOW, esperando comando.
  }
  
  state Multiplexando {
      [*] --> Ciclo_Activo
      Ciclo_Activo --> Ciclo_Activo : Recorre Fila por Fila (updateLEDs)
      state Note: Alta Actividad de I/O para alimentar los LEDs.
  }