%%{init: {'theme': 'default'}}%%
graph TD
    Usuario((Usuario))
    AppWeb((Aplicación Web Móvil))
    ESP32((Módulo de Control Físico))

    %% Casos de uso
    gestionarConexion[[Gestionar Enlace Inalámbrico BLE]]
    controlIndividual[[Controlar Posición de Luz Individual]]
    controlMasivo[[Controlar Conjunto de Luces]]
    monitorearBateria[[Monitorear Nivel de Batería]]
    
    %% Relaciones
    Usuario --> AppWeb
    
    AppWeb --> gestionarConexion
    AppWeb --> controlIndividual
    AppWeb --> controlMasivo
    AppWeb --> monitorearBateria
    
    controlIndividual -->|Envío de Datos de Estado| ESP32 
    controlMasivo -->|Envío de Datos de Estado| ESP32 
    
    ESP32 -->|Mide Señal de Voltaje| monitorearBateria
    
    ESP32 -.->|Reporte de Voltaje| AppWebs